apiVersion: apps/v1
kind: Deployment
metadata:
  name: lis-coresamples-v2-deployment-staging
  namespace: default
  labels:
    app: lis-coresamples-v2-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lis-coresamples-v2-staging
  template:
    metadata:
      labels:
        app: lis-coresamples-v2-staging
    spec:
      containers:
      - name: lis-coresamples-v2-staging
        image: 192.168.60.10:6004/vibrant/lis/coresamples-v2:staging
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8083
          initialDelaySeconds: 20
          periodSeconds: 80
          timeoutSeconds: 20
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8083
          initialDelaySeconds: 20
          periodSeconds: 5
        ports:
        - containerPort: 8084
        - containerPort: 8083
        env:
        - name: CONSUL_TOKEN
          valueFrom:
            secretKeyRef:
              name: lis-coresamples-secret
              key: CONSUL_TOKEN     
        - name: CORESAMPLES_ENV
          valueFrom:
            configMapKeyRef:
              name: lis-coresamples-config
              key: CORESAMPLES_ENV_STAGING
        - name: CONSUL_ADDR
          valueFrom:
            configMapKeyRef:
              name: lis-coresamples-config
              key: CONSUL_ADDR
        - name: CONSUL_PREFIX
          valueFrom:
            configMapKeyRef:
              name: lis-coresamples-config
              key: CONSUL_PREFIX