// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"coresamples/ent/patientflag"
	"coresamples/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PatientFlagDelete is the builder for deleting a PatientFlag entity.
type PatientFlagDelete struct {
	config
	hooks    []Hook
	mutation *PatientFlagMutation
}

// Where appends a list predicates to the PatientFlagDelete builder.
func (pfd *PatientFlagDelete) Where(ps ...predicate.PatientFlag) *PatientFlagDelete {
	pfd.mutation.Where(ps...)
	return pfd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pfd *PatientFlagDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pfd.sqlExec, pfd.mutation, pfd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pfd *PatientFlagDelete) ExecX(ctx context.Context) int {
	n, err := pfd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pfd *PatientFlagDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(patientflag.Table, sqlgraph.NewFieldSpec(patientflag.FieldID, field.TypeInt))
	if ps := pfd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pfd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pfd.mutation.done = true
	return affected, err
}

// PatientFlagDeleteOne is the builder for deleting a single PatientFlag entity.
type PatientFlagDeleteOne struct {
	pfd *PatientFlagDelete
}

// Where appends a list predicates to the PatientFlagDelete builder.
func (pfdo *PatientFlagDeleteOne) Where(ps ...predicate.PatientFlag) *PatientFlagDeleteOne {
	pfdo.pfd.mutation.Where(ps...)
	return pfdo
}

// Exec executes the deletion query.
func (pfdo *PatientFlagDeleteOne) Exec(ctx context.Context) error {
	n, err := pfdo.pfd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{patientflag.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pfdo *PatientFlagDeleteOne) ExecX(ctx context.Context) {
	if err := pfdo.Exec(ctx); err != nil {
		panic(err)
	}
}
