// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"coresamples/ent/rbacactions"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RBACActionsCreate is the builder for creating a RBACActions entity.
type RBACActionsCreate struct {
	config
	mutation *RBACActionsMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (rac *RBACActionsCreate) SetName(s string) *RBACActionsCreate {
	rac.mutation.SetName(s)
	return rac
}

// Mutation returns the RBACActionsMutation object of the builder.
func (rac *RBACActionsCreate) Mutation() *RBACActionsMutation {
	return rac.mutation
}

// Save creates the RBACActions in the database.
func (rac *RBACActionsCreate) Save(ctx context.Context) (*RBACActions, error) {
	return withHooks(ctx, rac.sqlSave, rac.mutation, rac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rac *RBACActionsCreate) SaveX(ctx context.Context) *RBACActions {
	v, err := rac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rac *RBACActionsCreate) Exec(ctx context.Context) error {
	_, err := rac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rac *RBACActionsCreate) ExecX(ctx context.Context) {
	if err := rac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rac *RBACActionsCreate) check() error {
	if _, ok := rac.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RBACActions.name"`)}
	}
	if v, ok := rac.mutation.Name(); ok {
		if err := rbacactions.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RBACActions.name": %w`, err)}
		}
	}
	return nil
}

func (rac *RBACActionsCreate) sqlSave(ctx context.Context) (*RBACActions, error) {
	if err := rac.check(); err != nil {
		return nil, err
	}
	_node, _spec := rac.createSpec()
	if err := sqlgraph.CreateNode(ctx, rac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rac.mutation.id = &_node.ID
	rac.mutation.done = true
	return _node, nil
}

func (rac *RBACActionsCreate) createSpec() (*RBACActions, *sqlgraph.CreateSpec) {
	var (
		_node = &RBACActions{config: rac.config}
		_spec = sqlgraph.NewCreateSpec(rbacactions.Table, sqlgraph.NewFieldSpec(rbacactions.FieldID, field.TypeInt))
	)
	_spec.OnConflict = rac.conflict
	if value, ok := rac.mutation.Name(); ok {
		_spec.SetField(rbacactions.FieldName, field.TypeString, value)
		_node.Name = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RBACActions.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RBACActionsUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (rac *RBACActionsCreate) OnConflict(opts ...sql.ConflictOption) *RBACActionsUpsertOne {
	rac.conflict = opts
	return &RBACActionsUpsertOne{
		create: rac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RBACActions.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rac *RBACActionsCreate) OnConflictColumns(columns ...string) *RBACActionsUpsertOne {
	rac.conflict = append(rac.conflict, sql.ConflictColumns(columns...))
	return &RBACActionsUpsertOne{
		create: rac,
	}
}

type (
	// RBACActionsUpsertOne is the builder for "upsert"-ing
	//  one RBACActions node.
	RBACActionsUpsertOne struct {
		create *RBACActionsCreate
	}

	// RBACActionsUpsert is the "OnConflict" setter.
	RBACActionsUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *RBACActionsUpsert) SetName(v string) *RBACActionsUpsert {
	u.Set(rbacactions.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RBACActionsUpsert) UpdateName() *RBACActionsUpsert {
	u.SetExcluded(rbacactions.FieldName)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RBACActions.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RBACActionsUpsertOne) UpdateNewValues() *RBACActionsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RBACActions.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RBACActionsUpsertOne) Ignore() *RBACActionsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RBACActionsUpsertOne) DoNothing() *RBACActionsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RBACActionsCreate.OnConflict
// documentation for more info.
func (u *RBACActionsUpsertOne) Update(set func(*RBACActionsUpsert)) *RBACActionsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RBACActionsUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *RBACActionsUpsertOne) SetName(v string) *RBACActionsUpsertOne {
	return u.Update(func(s *RBACActionsUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RBACActionsUpsertOne) UpdateName() *RBACActionsUpsertOne {
	return u.Update(func(s *RBACActionsUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *RBACActionsUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RBACActionsCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RBACActionsUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RBACActionsUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RBACActionsUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RBACActionsCreateBulk is the builder for creating many RBACActions entities in bulk.
type RBACActionsCreateBulk struct {
	config
	err      error
	builders []*RBACActionsCreate
	conflict []sql.ConflictOption
}

// Save creates the RBACActions entities in the database.
func (racb *RBACActionsCreateBulk) Save(ctx context.Context) ([]*RBACActions, error) {
	if racb.err != nil {
		return nil, racb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(racb.builders))
	nodes := make([]*RBACActions, len(racb.builders))
	mutators := make([]Mutator, len(racb.builders))
	for i := range racb.builders {
		func(i int, root context.Context) {
			builder := racb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RBACActionsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, racb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = racb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, racb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, racb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (racb *RBACActionsCreateBulk) SaveX(ctx context.Context) []*RBACActions {
	v, err := racb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (racb *RBACActionsCreateBulk) Exec(ctx context.Context) error {
	_, err := racb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (racb *RBACActionsCreateBulk) ExecX(ctx context.Context) {
	if err := racb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RBACActions.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RBACActionsUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (racb *RBACActionsCreateBulk) OnConflict(opts ...sql.ConflictOption) *RBACActionsUpsertBulk {
	racb.conflict = opts
	return &RBACActionsUpsertBulk{
		create: racb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RBACActions.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (racb *RBACActionsCreateBulk) OnConflictColumns(columns ...string) *RBACActionsUpsertBulk {
	racb.conflict = append(racb.conflict, sql.ConflictColumns(columns...))
	return &RBACActionsUpsertBulk{
		create: racb,
	}
}

// RBACActionsUpsertBulk is the builder for "upsert"-ing
// a bulk of RBACActions nodes.
type RBACActionsUpsertBulk struct {
	create *RBACActionsCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RBACActions.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RBACActionsUpsertBulk) UpdateNewValues() *RBACActionsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RBACActions.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RBACActionsUpsertBulk) Ignore() *RBACActionsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RBACActionsUpsertBulk) DoNothing() *RBACActionsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RBACActionsCreateBulk.OnConflict
// documentation for more info.
func (u *RBACActionsUpsertBulk) Update(set func(*RBACActionsUpsert)) *RBACActionsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RBACActionsUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *RBACActionsUpsertBulk) SetName(v string) *RBACActionsUpsertBulk {
	return u.Update(func(s *RBACActionsUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RBACActionsUpsertBulk) UpdateName() *RBACActionsUpsertBulk {
	return u.Update(func(s *RBACActionsUpsert) {
		s.UpdateName()
	})
}

// Exec executes the query.
func (u *RBACActionsUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RBACActionsCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RBACActionsCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RBACActionsUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
