// Code generated by ent, DO NOT EDIT.

package ent

import (
	"coresamples/ent/sample"
	"coresamples/ent/tuberequirement"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TubeRequirement is the model entity for the TubeRequirement schema.
type TubeRequirement struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SampleID holds the value of the "sample_id" field.
	SampleID int `json:"sample_id,omitempty"`
	// TubeType holds the value of the "tube_type" field.
	TubeType string `json:"tube_type,omitempty"`
	// RequiredCount holds the value of the "required_count" field.
	RequiredCount int `json:"required_count,omitempty"`
	// RequiredCountCreateTime holds the value of the "required_count_create_time" field.
	RequiredCountCreateTime time.Time `json:"required_count_create_time,omitempty"`
	// RequiredBy holds the value of the "required_by" field.
	RequiredBy string `json:"required_by,omitempty"`
	// ModifiedBy holds the value of the "modified_by" field.
	ModifiedBy string `json:"modified_by,omitempty"`
	// ModifiedTime holds the value of the "modified_time" field.
	ModifiedTime time.Time `json:"modified_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TubeRequirementQuery when eager-loading is set.
	Edges        TubeRequirementEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TubeRequirementEdges holds the relations/edges for other nodes in the graph.
type TubeRequirementEdges struct {
	// Sample holds the value of the sample edge.
	Sample *Sample `json:"sample,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SampleOrErr returns the Sample value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TubeRequirementEdges) SampleOrErr() (*Sample, error) {
	if e.loadedTypes[0] {
		if e.Sample == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: sample.Label}
		}
		return e.Sample, nil
	}
	return nil, &NotLoadedError{edge: "sample"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TubeRequirement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tuberequirement.FieldID, tuberequirement.FieldSampleID, tuberequirement.FieldRequiredCount:
			values[i] = new(sql.NullInt64)
		case tuberequirement.FieldTubeType, tuberequirement.FieldRequiredBy, tuberequirement.FieldModifiedBy:
			values[i] = new(sql.NullString)
		case tuberequirement.FieldRequiredCountCreateTime, tuberequirement.FieldModifiedTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TubeRequirement fields.
func (tr *TubeRequirement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tuberequirement.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			tr.ID = int(value.Int64)
		case tuberequirement.FieldSampleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sample_id", values[i])
			} else if value.Valid {
				tr.SampleID = int(value.Int64)
			}
		case tuberequirement.FieldTubeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tube_type", values[i])
			} else if value.Valid {
				tr.TubeType = value.String
			}
		case tuberequirement.FieldRequiredCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field required_count", values[i])
			} else if value.Valid {
				tr.RequiredCount = int(value.Int64)
			}
		case tuberequirement.FieldRequiredCountCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field required_count_create_time", values[i])
			} else if value.Valid {
				tr.RequiredCountCreateTime = value.Time
			}
		case tuberequirement.FieldRequiredBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field required_by", values[i])
			} else if value.Valid {
				tr.RequiredBy = value.String
			}
		case tuberequirement.FieldModifiedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field modified_by", values[i])
			} else if value.Valid {
				tr.ModifiedBy = value.String
			}
		case tuberequirement.FieldModifiedTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field modified_time", values[i])
			} else if value.Valid {
				tr.ModifiedTime = value.Time
			}
		default:
			tr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TubeRequirement.
// This includes values selected through modifiers, order, etc.
func (tr *TubeRequirement) Value(name string) (ent.Value, error) {
	return tr.selectValues.Get(name)
}

// QuerySample queries the "sample" edge of the TubeRequirement entity.
func (tr *TubeRequirement) QuerySample() *SampleQuery {
	return NewTubeRequirementClient(tr.config).QuerySample(tr)
}

// Update returns a builder for updating this TubeRequirement.
// Note that you need to call TubeRequirement.Unwrap() before calling this method if this TubeRequirement
// was returned from a transaction, and the transaction was committed or rolled back.
func (tr *TubeRequirement) Update() *TubeRequirementUpdateOne {
	return NewTubeRequirementClient(tr.config).UpdateOne(tr)
}

// Unwrap unwraps the TubeRequirement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tr *TubeRequirement) Unwrap() *TubeRequirement {
	_tx, ok := tr.config.driver.(*txDriver)
	if !ok {
		panic("ent: TubeRequirement is not a transactional entity")
	}
	tr.config.driver = _tx.drv
	return tr
}

// String implements the fmt.Stringer.
func (tr *TubeRequirement) String() string {
	var builder strings.Builder
	builder.WriteString("TubeRequirement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tr.ID))
	builder.WriteString("sample_id=")
	builder.WriteString(fmt.Sprintf("%v", tr.SampleID))
	builder.WriteString(", ")
	builder.WriteString("tube_type=")
	builder.WriteString(tr.TubeType)
	builder.WriteString(", ")
	builder.WriteString("required_count=")
	builder.WriteString(fmt.Sprintf("%v", tr.RequiredCount))
	builder.WriteString(", ")
	builder.WriteString("required_count_create_time=")
	builder.WriteString(tr.RequiredCountCreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("required_by=")
	builder.WriteString(tr.RequiredBy)
	builder.WriteString(", ")
	builder.WriteString("modified_by=")
	builder.WriteString(tr.ModifiedBy)
	builder.WriteString(", ")
	builder.WriteString("modified_time=")
	builder.WriteString(tr.ModifiedTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TubeRequirements is a parsable slice of TubeRequirement.
type TubeRequirements []*TubeRequirement
